In [1]:
import pandas as pd

fraud = pd.read_csv("../data/raw/Fraud_Data.csv")

fraud['signup_time'] = pd.to_datetime(fraud['signup_time'])
fraud['purchase_time'] = pd.to_datetime(fraud['purchase_time'])

fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,34,QVPSPJUOCKZAR,SEO,Chrome,M,39,7.327584e+08,0
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,16,EOGFQPIZPYXFZ,Ads,Chrome,F,53,3.503114e+08,0
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,15,YSSKYOSJHPPLJ,SEO,Opera,M,53,2.621474e+09,1
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,44,ATGTXKYKUDUQN,SEO,Safari,M,41,3.840542e+09,0
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,39,NAUITBZFJKHWW,Ads,Safari,M,45,4.155831e+08,0

In [2]:
fraud['time_since_signup'] = (
    fraud['purchase_time'] - fraud['signup_time']
).dt.total_seconds()

In [3]:
fraud['hour_of_day'] = fraud['purchase_time'].dt.hour

In [4]:
fraud['day_of_week'] = fraud['purchase_time'].dt.dayofweek

In [5]:
fraud['user_transaction_count'] = fraud.groupby('user_id')['user_id'].transform('count')

In [6]:
fraud['device_transaction_count'] = fraud.groupby('device_id')['device_id'].transform('count')

In [7]:
fraud['ip_address_int'] = fraud['ip_address'].astype(int)

In [8]:
fraud[['time_since_signup',
       'hour_of_day',
       'day_of_week',
       'user_transaction_count',
       'device_transaction_count']].head()

,time_since_signup,hour_of_day,day_of_week,user_transaction_count,device_transaction_count
0,4506682.0,2,5,1,1
1,17944.0,1,0,1,1
2,1.0,18,3,1,12
3,492085.0,13,0,1,1
4,4361461.0,18,2,1,1

Feature engineering was applied to extract behavioral signals from raw transaction data. Time-based features such as time_since_signup and hour_of_day capture temporal fraud patterns, while frequency-based features such as user_transaction_count and device_transaction_count help identify abnormal repeated behavior often associated with fraudulent activity.